[package]
name = "mirl_codec_info"
version = "0.0.0-alpha"
edition.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

exclude = ["./tests"]

[dependencies]
serde_json = { version = ">=1", optional = true }
mirl_core = { version = "0.0.0-alpha" }
mirl_values = { version = "0.0.0-alpha" }
mirl_extensions = { version = "0.0.0-alpha" }

indexmap = { version = ">=2", optional = true }
# strum = { version = ">=0.26", optional = true, features = ["derive"] }

mirl_derive = { version = "0.0.0-alpha", optional = true }
# Codec
compactly = { version = "0.1.6", optional = true }
serde = { version = ">=1.0", optional = true, default-features = false, features = [
    "derive",
] }
bitcode = { version = "0.6.9", optional = true, default-features = false, features = [
    "derive",
] }
wincode = { version = "0.4.5", optional = true, default-features = false, features = [
    "derive",
] }
zerocopy = { version = "0.8.48", optional = true, default-features = false, features = [
    "float-nightly",
    "derive",
] }

# # Enum functionality
# strum = { version = ">=0.28", optional = true, default-features = false, features = [
#     "derive",
# ] }
# enum_ext = { version = "0.5.2", optional = true, default-features = false }


[features]
#default = ["serde", "strum"]
default = []
all = ["all_codecs"]
# preserve_entries = ["dep:indexmap", "mirl_values/preserve_entries"]

# Does nothing by itself. Needs another codec or enum flag to do something
mirl_derive = ["dep:mirl_derive"]
# Compatibility with ffi
c_compatible = ["mirl_derive"]
# Enables all codecs
all_codecs = ["serde", "bitcode", "wincode", "compactly", "zerocopy"]
# # All enum extensions
# all_enum_extensions = ["strum", "enum_ext"]

# Codec stuff
serde = ["dep:serde", "mirl_derive", "mirl_core/serde", "mirl_values/serde"]
bitcode = [
    "dep:bitcode",
    "mirl_derive",
    "mirl_core/bitcode",
    "mirl_values/bitcode",
]
wincode = [
    "dep:wincode",
    "mirl_derive",
    "mirl_core/wincode",
    "mirl_values/wincode",
]
compactly = [
    "dep:compactly",
    "mirl_derive",
    "mirl_core/compactly",
    "mirl_values/compactly",
]
zerocopy = [
    "dep:zerocopy",
    "mirl_derive",
    "mirl_core/zerocopy",
    "mirl_values/zerocopy",
]

# # Enum extensions
# strum = ["dep:strum", "mirl_derive"]
# enum_ext = ["dep:enum_ext", "mirl_derive"]
[build-dependencies]
mirl_build_tools = { workspace = true }

[dev-dependencies]
# strum = true
rayon = "1.7"
num_cpus = "1.16"
